name = "mekuri"
main = "./src/index.ts"
compatibility_date = "2025-02-27"

[observability]
enabled = true
head_sampling_rate = 0.1

[triggers]
crons = ["0 20 * * *",
          "45 20 * * *",
          "0 21 * * *"]