name = "mekuri"
main = "./src/index.ts"
compatibility_date = "2025-02-27"

[observability]
enabled = true
head_sampling_rate = 0.1

[observability.logs]
enabled = true

[triggers]
crons = ["0 11 * * tue",
          "45 11 * * tue",
          "0 12 * * tue"]